name: pwa_virtualized_list
description: A Flutter package for rendering large scrollable lists efficiently by showing only visible items. Ideal for PWAs.
version: 1.0.3
homepage: https://github.com/matinmaya/pwa_virtualized_list 
repository: https://github.com/matinmaya/pwa_virtualized_list 
issue_tracker: https://github.com/matinmaya/pwa_virtualized_list/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DummyPlugin

