name: pwa_virtualized_list
description: >
  A Flutter package that provides a virtualized list widget optimized for Progressive Web Apps (PWAs). This package is designed to handle large lists efficiently by rendering only the visible items, improving performance and user experience in web applications.
  This package is particularly useful for applications that require displaying extensive lists of data without compromising on performance, making it ideal for PWAs built with Flutter.
version: 1.0.1
homepage: https://github.com/matinmaya/pwa_virtualized_list 
repository: https://github.com/matinmaya/pwa_virtualized_list 
issue_tracker: https://github.com/matinmaya/pwa_virtualized_list/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DummyPlugin

